name: Go Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
      id: go

    - uses: actions/checkout@v2

    - name: Build
      run: go build -v -o urlshortener .

    - name: Tar Files
      run: tar -czvf latest-linux-amd64.tar.gz urlshortener

    - name: 'Upload Linux x64 Release'
      uses: actions/upload-artifact@v2
      with:
        name: latest-linux-amd64-build
        path: latest-linux-amd64.tar.gz
