name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mariadb:10.5.5
        env:
          MYSQL_ROOT_PASSWORD: '12345678'
          MYSQL_USER: 'shortener'
          MYSQL_PASSWORD: '12345678'
          MYSQL_DATABASE: 'shortener_db'
        ports:
        - 32574:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
      id: go

    - uses: actions/checkout@v2

    - name: Install ginkgo
      run: go get github.com/onsi/ginkgo/ginkgo

    - name: Test
      env:
        TEST_STORAGE: mysql
        MYSQL_HOST: mariadb
        MYSQL_DBNAME: shortener_db
        MYSQL_USER: root
        MYSQL_PASSWORD: '12345678'
      run: ginkgo -race -progress ./...

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
      id: go

    - uses: actions/checkout@v2

    - name: Build
      run: go build -v -o urlshortener .

    - name: Tar Files
      run: tar -czvf latest-linux-amd64.tar.gz urlshortener

    - name: 'Upload Linux x64 Release'
      uses: actions/upload-artifact@v2
      with:
        name: latest-linux-amd64-build
        path: latest-linux-amd64.tar.gz
