name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mariadb:10.5.5
        env:
          MYSQL_ROOT_PASSWORD: '12345678'
          MYSQL_USER: 'shortener'
          MYSQL_PASSWORD: '12345678'
          MYSQL_DATABASE: 'shortener_db'
        ports:
        - 32574:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
      id: go

    - uses: actions/checkout@v2

    #- name: Install ginkgo
    #  run: go get github.com/onsi/ginkgo/ginkgo

    - name: Test with In-Memory Storage
      #run: ginkgo -race -progress -r
      run: go test -v  -coverprofile=coverage1.txt -covermode=atomic ./...

    - name: Test with MariaDB Storage
      env:
        TEST_STORAGE: mysql
        MYSQL_HOST: 127.0.0.1:32574
        MYSQL_DBNAME: shortener_db
        MYSQL_USER: root
        MYSQL_PASSWORD: '12345678'
      #run: ginkgo -race -progress -r
      run: go test -v  -coverprofile=coverage2.txt -covermode=atomic ./...

    - name: Install gocovmerge
      run: go get -u github.com/wadey/gocovmerge
    
    - name: Combine coverage results
      run: |
        gocovmerge coverage1.txt coverage2.txt > coverage.txt
        rm coverage1.txt coverage2.txt

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1

    - name: Run Vet & Lint
      run: go vet .
